[profile.default]
src = "contract/src"
test = "contract/test"
out = "contract/forge-artifacts"
script = "contract/script"
cache_path = "contract/cache"
broadcast = "contract/broadcast"
libs = [ "contract/lib" ]
solc_version = "0.8.28"
remappings = [
  "@openzeppelin/contracts/=contract/lib/openzeppelin-contracts/contracts/",
  "@prb/math/=contract/lib/prb-math/src/"
]

[lint]
exclude_lints = [ "screaming-snake-case-immutable" ]
ignore = [
  "contract/test/**/*",
  "contract/script/**/*"
]
